### ISSUE TITLE
[Flaw/Bug]: Spam of error messages

### ISSUE THREAD

**Issue by Palloxin** [Sigil-Ebook/Sigil#795]
### Bug Description

![Image](https://github.com/user-attachments/assets/958af8e2-7298-42ab-b085-5137c49a85d6)

![Image](https://github.com/user-attachments/assets/3d19d2c5-3433-467f-ba05-f6fecbc54cbc)

Sigils just spams error messages for EVERY single error (images).
Please make Sigil do a summary.

I used calibre to merge 40 epb in one and then open with sigil. I had to click "ok" 80 times. Spamming the error like that is just... not ideal.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

10

### What version of Sigil are you using?

2.3.1

### Any backtraces or crash reports

```shell

```

**Comment by dougmassay** [comment]
A) don't feed Sigil crap with incorrect media types
B) this is fixed and will be in Sigil's next release https://github.com/Sigil-Ebook/Sigil/issues/791

Please search the closed issues as well before submitting bug reports to avoid duplicates.

**Comment by kevinhendricks** [comment]
Actually it is fixed in Sigil 2.4.2

**Comment by dougmassay** [comment]
You're right. I forgot!

I can't understand why people report bugs for anything but the latest version. Verifying it still exists me n the latest released version should be the first step, no?

**Comment by kevinhendricks** [comment]
I can't understand why anyone would use an epub generating tool that makes up completely fake OPF media types.  Both the epub2 and the epub3 have long included a list of media-types that should be used.

Just some really bad generating software at work where the authors have not bothered to read or follow the specs.  The OP should instead file a bug report about fake media-types in whatever software they are using that generated them.

Typically missing or bad media-types are rare in commercial grade epubs  but 80 of them is unheard of.  They are of course different errors, not just a single error as the OPF manifest would need to be edited in 80 different places with the correct media-types for that specific resource.

**Comment by BeckyDTP** [comment]
FYI (and for future users who will be shown such media types in the details): 
```
content.opf ('origrootfile/xml' -> 'application/oebps-package+xml')
toc.ncx ('origtocncx/xml' -> 'application/x-dtbncx+xml')
```

Copies of the original files OPF/NCX are indeed created by the plugin [EpubMerge](https://www.mobileread.com/forums/showthread.php?t=169744) [[github](https://github.com/JimmXinu/EpubMerge)]

Adding these files: [Here](https://github.com/JimmXinu/EpubMerge/blob/4858fa0e57f3808a94541a67bd8b84dbb3210fc6/epubmerge/epubmerge.py#L464), and [here](https://github.com/JimmXinu/EpubMerge/blob/4858fa0e57f3808a94541a67bd8b84dbb3210fc6/epubmerge/epubmerge.py#L501).

The user can disable the creation of these copies in the plugin settings:
![Image](https://github.com/user-attachments/assets/57d375d3-8b85-47d5-beef-c6c446fff8d8)

**Comment by dougmassay** [comment]
So it's actually a matter of users not knowing how to properly use the 3rd-party Calibre EpubMerge plugin and then bringing their complaints to Sigil after they've managed to generate a garbage epub thenselves?! 

Thanks! At least now we know where to send people when/if this crops up again.

**Comment by Palloxin** [comment]
Not sure how Sigil fixes them(maybe u mean enough to make it editable on sigil). If I open such an epub with the said problem and then..
1. click save
2. close Sigil
3. re-open the freshly saved epub

The problem will still be there. Since 2.4.2 fixes it, it's no longer a hassle anyway.

**Comment by dougmassay** [comment]
Sigil 2.4.2 doesn't technically fix the issue. It just combines all of the errors into one. It then "fixes" the fictitious media types that the "Save UnMerge Metadata" option of Epubmerge creates. That "Fix" breaks any possibility of ever being able to use that metadata to unmerge the created anthology. So if you need to edit one of these anthologies created with Epubmerge in anything other than Calibre, it's in your best interest to uncheck the "Save UnMerge Metadata" option in EpubMerge's configuration.
